# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/akcopema/Documents/ECE495/Examples/Unit1/unit1/unit1.cache/wt [current_project]
set_property parent.project_path /home/akcopema/Documents/ECE495/Examples/Unit1/unit1/unit1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  /home/akcopema/Documents/ECE495/Examples/Unit1/mybcd_udcount.vhd
  /home/akcopema/Documents/ECE495/Examples/Unit1/my_genpulse.vhd
  /home/akcopema/Documents/ECE495/Examples/Unit1/mybcd_udcount_top.vhd
}
read_xdc /home/akcopema/Documents/ECE495/Examples/Unit1/ZYBO_Master.xdc
set_property used_in_implementation false [get_files /home/akcopema/Documents/ECE495/Examples/Unit1/ZYBO_Master.xdc]

synth_design -top mybcd_udcount_top -part xc7z010clg400-1
write_checkpoint -noxdef mybcd_udcount_top.dcp
catch { report_utilization -file mybcd_udcount_top_utilization_synth.rpt -pb mybcd_udcount_top_utilization_synth.pb }
