# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/Pix_proc_full_examp/Pix_proc_full_examp.cache/wt [current_project]
set_property parent.project_path C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/Pix_proc_full_examp/Pix_proc_full_examp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/pack_xtras.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/LUT_NIto1.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/LUT_NItoNO.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/LUT_group.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/static_ip.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/my_genpulse_sclr.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/my_AXImem.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/my_AXIfifo.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/myAXI_IP.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/mypixfull_v1_0_S00_AXI.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Examples/pix_proc_full/mypixfull_v1_0.vhd
}
synth_design -top mypixfull_v1_0 -part xc7z010clg400-1
write_checkpoint -noxdef mypixfull_v1_0.dcp
catch { report_utilization -file mypixfull_v1_0_utilization_synth.rpt -pb mypixfull_v1_0_utilization_synth.pb }
