# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/edit_myCORDIC_full_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/edit_myCORDIC_full_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/lpm_pack.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/fulladd.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/my_addsub.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/my4to1LUT_atan.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/lpm_clshift.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/mux_2to1.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/my_rege.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/CORDIC_FP_top.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/edit_myCORDIC_full_v1_0.srcs/sources_1/new/cordic_ip.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/my_genpulse_sclr.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/my_AXIfifo.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/myCORDIC_full_1.0/hdl/myAXI_IP.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/mycordic_full_1.0/hdl/myCORDIC_full_v1_0_S00_AXI.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab5/ip_repo/mycordic_full_1.0/hdl/myCORDIC_full_v1_0.vhd
}
synth_design -top myCORDIC_full_v1_0 -part xc7z010clg400-1
write_checkpoint -noxdef myCORDIC_full_v1_0.dcp
catch { report_utilization -file myCORDIC_full_v1_0_utilization_synth.rpt -pb myCORDIC_full_v1_0_utilization_synth.pb }
