webtalk_init -webtalk_dir C:\\Users\\mr_co_000\\Documents\\GitHub\\ECE495\\FinalProject\\Filter\\filter\\filter.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 10 17:41:00 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hm9ns5rk6imuodvvbcevj2gjfb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1449781765453" -context "sdk\\\\bsp/1449781765453"
webtalk_add_data -client sdk -key hwid -value "1449259146694" -context "sdk\\\\bsp/1449781765453"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1449781765453"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1449781765453"
webtalk_add_data -client sdk -key uid -value "1449781769213" -context "sdk\\\\application/1449781769213"
webtalk_add_data -client sdk -key hwid -value "1449259146694" -context "sdk\\\\application/1449781769213"
webtalk_add_data -client sdk -key bspid -value "1449781765453" -context "sdk\\\\application/1449781769213"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1449781769213"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1449781769213"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1449781769213"
webtalk_transmit -clientid 2401390131 -regid "" -xml C:\\Users\\mr_co_000\\Documents\\GitHub\\ECE495\\FinalProject\\Filter\\filter\\filter.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\mr_co_000\\Documents\\GitHub\\ECE495\\FinalProject\\Filter\\filter\\filter.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\mr_co_000\\Documents\\GitHub\\ECE495\\FinalProject\\Filter\\filter\\filter.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
