# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/mr_co_000/documents/github/ece495/lab/lab4/lab4/lab4.tmp/mycordic_v1_0_project/mycordic_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/mr_co_000/documents/github/ece495/lab/lab4/lab4/lab4.tmp/mycordic_v1_0_project/mycordic_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/mr_co_000/Documents/GitHub/ECE495/Lab/Lab4/ip_repo/mycordic_1.0 [current_project]
read_vhdl -library xil_defaultlib {
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/lpm_pack.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/fulladd.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/my4to1LUT_atan.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/mux_2to1.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/my_rege.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/my_addsub.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/lpm_clshift.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/CORDIC_FP_top.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/Cordic_top.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/mycordic_v1_0_S00_AXI.vhd
  c:/users/mr_co_000/documents/github/ece495/lab/lab4/ip_repo/mycordic_1.0/hdl/mycordic_v1_0.vhd
}
synth_design -top mycordic_v1_0 -part xc7z010clg400-1
write_checkpoint -noxdef mycordic_v1_0.dcp
catch { report_utilization -file mycordic_v1_0_utilization_synth.rpt -pb mycordic_v1_0_utilization_synth.pb }
