# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/pix_proc.cache/wt [current_project]
set_property parent.project_path C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/pix_proc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/pack_xtras.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/LUT_NIto1.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/LUT_NItoNO.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/LUT_group.vhd
  C:/Users/mr_co_000/Documents/GitHub/ECE495/Homework/Homework3/pix_proc/test.vhd
}
synth_design -top test -part xc7z020clg484-1
write_checkpoint -noxdef test.dcp
catch { report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb }
